#!/usr/bin/env python3
"""Index everything in outputs/, with its verdict and provenance.

Artefacts accumulate one role at a time and there was no way to see what exists,
which was screened, and which is stale. Regenerate with `make index`.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from current_pack import resolve, sha256, ROOT  # noqa: E402

OUTPUTS = ROOT / "outputs"


def rows():
    current = resolve()
    current_sha = sha256(current) if current else None
    for draft in sorted(OUTPUTS.glob("*-draft.md")):
        stem = draft.name[: -len("-draft.md")]
        ev = OUTPUTS / f"{stem}-evaluation.json"
        screen = OUTPUTS / f"{stem}-draft-screen.json"
        row = {"artifact": draft.name, "role": stem.replace("-", " "),
               "publishable": None, "verdict": None, "pack": None, "stale": None}
        if ev.exists():
            data = json.loads(ev.read_text())
            row["publishable"] = data.get("publishable")
            run = data.get("run") or {}
            row["pack"] = Path(run.get("pack", "")).name or None
            if run.get("pack_sha256") and current_sha:
                row["stale"] = run["pack_sha256"] != current_sha
        if screen.exists():
            row["verdict"] = json.loads(screen.read_text()).get("verdict")
        yield row


def markdown():
    out = ["# Artefacts", "",
           "Generated by `make index`. Verdict comes from the recruiter screen;",
           "stale means the pack has changed since the artefact was evaluated.", "",
           "| Artefact | Role | Publishable | Verdict | Pack | Stale |",
           "| --- | --- | --- | --- | --- | --- |"]
    empty = True
    for row in rows():
        empty = False
        fmt = lambda v: "-" if v is None else ("yes" if v is True else "no" if v is False else str(v))
        out.append(f"| `{row['artifact']}` | {row['role']} | {fmt(row['publishable'])} | "
                   f"{fmt(row['verdict'])} | {fmt(row['pack'])} | {fmt(row['stale'])} |")
    if empty:
        out.append("| _none yet_ | | | | | |")
    return "\n".join(out) + "\n"


def main(argv):
    if "--json" in argv:
        print(json.dumps(list(rows()), indent=2))
        return 0
    target = OUTPUTS / "INDEX.md"
    target.write_text(markdown())
    print(target.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
